import { PokemonProvider } from '@/store/context/usePokemonStore';
import './globals.css';
import type { Metadata } from 'next';
import { Karla } from 'next/font/google';

const karla = Karla({
  subsets: ['latin-ext'],
  variable: '--font-karla',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export interface Pokemon {
  id: number;
  name: string;
  image: string;
}

const getData = async () => {
  const resp = await fetch(
    'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
  );
  const pokemon: Pokemon[] = await resp.json();
  return pokemon;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pokemon = await getData();
  return (
    <html lang='en'>
      <body className={`${karla.className} bg-slate-300 p-5`}>
        <PokemonProvider pokemon={pokemon}>{children}</PokemonProvider>
      </body>
    </html>
  );
}
